# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-18 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('siblings', models.CharField(max_length=200)),
                ('exposures', models.CharField(default='None', max_length=200)),
                ('mutations', models.CharField(default='None', max_length=200)),
                ('status', models.CharField(default='Not Reviewed', max_length=200)),
            ],
        ),
    ]
